# Generated by Django 3.1.2 on 2020-10-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Follicle_r', models.DecimalField(decimal_places=2, max_digits=5, max_length=120)),
                ('Follicle_l', models.DecimalField(decimal_places=2, max_digits=5, max_length=120)),
                ('Skin_darkening', models.DecimalField(decimal_places=2, max_digits=5, max_length=120)),
                ('hair_growth', models.DecimalField(decimal_places=2, max_digits=5, max_length=120)),
                ('Weight_gain', models.DecimalField(decimal_places=2, max_digits=5, max_length=120)),
                ('Cycle', models.DecimalField(decimal_places=2, max_digits=5, max_length=120)),
            ],
        ),
    ]
